"use strict";
exports.__esModule = true;
var Car_1 = require("./Car");
var CarColors_1 = require("./CarColors");
var CarDirections_1 = require("./CarDirections");
var CarDoors_1 = require("./CarDoors");
var honda = new Car_1["default"]('Honda', CarColors_1["default"].SILVER, 4);
honda.openTheDoor(CarDoors_1["default"].DRIVER);
honda.closeTheDoor(CarDoors_1["default"].DRIVER);
honda.turnOn();
honda.speedUp();
honda.speedDown();
honda.turn(CarDirections_1["default"].LEFT);
honda.speedUp();
honda.speedDown();
honda.turn(CarDirections_1["default"].RIGHT);
honda.speedUp();
honda.speedDown();
honda.turn(CarDirections_1["default"].RIGHT);
honda.speedDown();
honda.stop();
honda.openTheDoor(CarDoors_1["default"].BEHIND_RIDER);
honda.closeTheDoor(CarDoors_1["default"].BEHIND_RIDER);
honda.speedUp();
honda.speedDown();
honda.turn(CarDirections_1["default"].RIGHT);
honda.speedUp();
honda.speedDown();
honda.turn(CarDirections_1["default"].LEFT);
honda.speedUp();
honda.speedDown();
honda.turn(CarDirections_1["default"].RIGHT);
honda.speedDown();
honda.stop();
honda.openTheDoor(CarDoors_1["default"].BEHIND_RIDER);
honda.closeTheDoor(CarDoors_1["default"].BEHIND_RIDER);
honda.speedUp();
